# This file is a template, and might need editing before it works on your project.
# Full project: https://gitlab.com/pages/plain-html
image: ruby:2.3

pages:
  stage: deploy
  script:
  - gem install jazzy -v 0.9.5
  - mkdir .public
  - cd Apple\ Pay\ Sample
  - jazzy --clean --author HyreCar --theme fullwidth --documentation=../*.md --output ../public/docs --no-hide-documentation-coverage --min-acl private 
  - cp -r * .public
  - mv .public public
  artifacts:
    paths:
    - public
  only:
  - master
