documentation:
    @jazzy \
        --clean \
        --author HyreCar \
        --min-acl internal \
        --no-hide-documentation-coverage \
        --theme fullwidth \
        --output ../public/docs \
        --documentation ../*.md
    @rm -rf ./build